version: "3.9"

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - "./browsers.json:/etc/selenoid/browsers.json:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-limit", "4", "-timeout", "5m", "-service-startup-timeout", "2m","-session-attempt-timeout", "2m", "-retry-count", "2", "-capture-driver-logs"]

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    container_name: selenoid-ui
    depends_on:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  tests:
    build: .
    container_name: sprint_9_tests
    depends_on:
      - selenoid
    environment:
      SELENIUM_REMOTE_URL: "http://selenoid:4444/wd/hub"
      BROWSER_NAME: "chrome"
      BROWSER_VERSION: "128.0"
    volumes:
      - .:/app
    command: pytest tests -v --alluredir=allure-results